services:
  postgres:
    image: postgres:17
    container_name: lumiere-postgres
    environment:
      POSTGRES_DB: lumiere
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - lumiere-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d lumiere"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  lumiere-postgres-data:
